name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  distrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - actions/checkout@v2
        - uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.DEPLOY_KEY }}
            
      - name: setup python
        uses: actions/setup-python@v2.2.2

      - name: setup requirements
        run: |
          pip3 install Markdown pelican
          
      - name: distrib
        run: |
          TPUSER=${{ secrets.DEPLOY_USER }} TPHOST=${{ secrets.DEPLOY_HOST }} python3 distrib.py
          
