name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  distrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: add key
        run: echo ${DEPLOY_KEY} > ~/.ssh/id_rsa
        
      - name: setup python
        uses: actions/setup-python@v2.2.2

      - name: setup requirements
        run: |
          pip3 install Markdown pelican
          
      - name: distrib
        run: |
          TPUSER=${DEPLOY_USER} TPHOST=${DEPLOY_HOST} python3 distrib.py
          
