name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  distrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}       
          known_hosts: 'placeholder'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: setup python
        uses: actions/setup-python@v2.2.2

      - name: setup requirements
        run: |
          pip3 install Markdown pelican
          
      - name: distrib
        run: |
          TPUSER=${{ secrets.DEPLOY_USER }} TPHOST=${{ secrets.DEPLOY_HOST }} python3 distrib.py
          
